---
# Build Configuration
before_install: 
  - ./.tests/url-check.sh
install: []
before_script: []
script:
  - bundle exec jekyll build
after_script: []
  # - bundle exec ruby ./.tests/status-report/server.rb

